# resolver и upstream (они уже внутри http-контекста)
resolver 127.0.0.11 valid=5s;

upstream blog_upstream {
    zone blog_upstream 64k; 
    server ts-blog-frontend:3001 resolve;
}
# upstream для API блога
upstream blog_api_upstream {
    zone blog_api_upstream 64k;
    server ts-blog-backend:4200 resolve;
}

# редирект с HTTP на HTTPS
server {
    listen 80;
    server_name entergen.ru www.entergen.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# основной HTTPS-сервер
# server {
#     listen 443 ssl;
#     server_name entergen.ru www.entergen.ru;

#     ssl_certificate     /etc/letsencrypt/live/entergen.ru-0001/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/entergen.ru-0001/privkey.pem;
#     include             /etc/letsencrypt/options-ssl-nginx.conf;
#     ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

#     # основной фронт
#     location / {
#         proxy_pass http://entergen-frontend:3000;
#         proxy_set_header Host              $host;
#         proxy_set_header X-Real-IP         $remote_addr;
#         proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }

#     # блог на /blog
#     location /blog/ {
#         proxy_pass http://blog_upstream/;
#         proxy_set_header Host              $host;
#         proxy_set_header X-Real-IP         $remote_addr;
#         proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;

#         proxy_connect_timeout 3s;
#         proxy_read_timeout    10s;
#         proxy_send_timeout    10s;
#         proxy_intercept_errors on;
#     }
#     # API блога на /blog/api/
#     location /blog/api/ {
#         proxy_pass http://blog_api_upstream/;
#         proxy_set_header Host              $host;
#         proxy_set_header X-Real-IP         $remote_addr;
#         proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;

#         proxy_connect_timeout 3s;
#         proxy_read_timeout    10s;
#         proxy_send_timeout    10s;
#         proxy_intercept_errors on;
#     }

#     # API
#     location /api/ {
#         proxy_pass http://entergen-backend:8000/api/;
#         proxy_set_header Host              $host;
#         proxy_set_header X-Real-IP         $remote_addr;
#         proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_redirect off;
#     }
# }

