name: Trigger General Pipeline

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger general repo
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
          https://api.github.com/repos/ratnov2/todo_general/dispatches \
          -d '{"event_type":"backend_updated"}'
